--!strict

local Cart = {
	BodySize = Vector3.new(5, 1, 7),
	RideHeight = 2.5,
	ProbeLength = 3.5,
	ProbeInset = 0.65,
	GroundContactMargin = 0.35,
	MinSupportNormalY = 0.3,
	SupportSpring = 180,
	SupportDamping = 30,
	MaxSupportGravity = 4,
	SeparatingSpeed = 7,
	NormalResponse = 12,
	AlignmentResponse = 20,
	AirAlignmentResponse = 6,
	AlignmentTorquePerMass = 400,
	MaxAngularVelocity = 5,

	CruiseSpeed = 44,
	ReverseSpeed = 15,
	Acceleration = 38,
	ClimbAssist = 0.55,
	BrakeAcceleration = 95,
	CoastDeceleration = 14,
	RollingDeceleration = 0.65,
	GripResponse = 7,
	GripAcceleration = 220,
	DriftGripResponse = 1.25,
	DriftGripAcceleration = 65,
	DriftMaxSlip = math.rad(70),
	DriftAcceleration = 4,
	DriftMaxSpeedGain = 8,
	TurnRate = 1.9,
	DriftTurnRate = 2.7,
	SteerReferenceSpeed = 13,
	SteeringResponse = 18,
	FullLoadAccelerationLoss = 0.30,
	FullLoadBrakeLoss = 0.25,
	FullLoadSteeringLoss = 0.08,
	FullLoadCoastReduction = 0.15,
	AirTurnRate = 0.8,
	AirSteerRadians = 1.2,
	AirLateralAcceleration = 12,
	AirGravityScale = 0.5,
	DiveGravityScale = 2.2,

	SteeringDeadzone = 0.18,
	HopSpeed = 18,
	ChargedHopSpeed = 26,
	JumpChargeSeconds = 0.35,
	LedgeGraceSeconds = 0.1,
	HopSupportReleaseSeconds = 0.15,
	MinDriftSpeed = 14,
	MinDriftSlip = math.rad(8),
	DriftTierSeconds = { 0.7, 1.5 },
	DriftBoostSeconds = { 0.35, 0.65 },
	BoostAcceleration = 90,
	BoostSpeedGainPerSecond = 24,
	BoostMaxSpeedGain = 18,
	ArcadeSpeedCeiling = 120,
	BoostAirGraceSeconds = 1.5,
	MaxStepSeconds = 0.1,
}

table.freeze(Cart.DriftTierSeconds)
table.freeze(Cart.DriftBoostSeconds)

return table.freeze({ Cart = table.freeze(Cart) })
