--!strict

type GestureModule = typeof(require("../../packages/RideRuntime/Gesture"))
return function(Gesture: GestureModule)
	local config = {
		SteeringDeadzone = 0.15, HopSpeed = 10, ChargedHopSpeed = 20,
		JumpChargeSeconds = 0.4, LedgeGraceSeconds = 0.1,
		MinDriftSpeed = 8, MinDriftSlip = 0.15,
		DriftTierSeconds = {0.4, 0.9}, DriftBoostSeconds = {0.15, 0.4},
	}
	local passed = 0
	local function check(name, fn)
		local ok, err = pcall(fn)
		assert(ok, name .. ": " .. tostring(err))
		passed += 1
	end
	local function near(a, b) assert(math.abs(a-b) < 1e-8, tostring(a) .. " ~= " .. tostring(b)) end
	local function input(jump, drift, enabled)
		return {held = jump == true, drift = drift == true, enabled = enabled ~= false}
	end
	local ground = {grounded = true, speed = 16, slip = 0.3}
	local air = {grounded = false, speed = 16, slip = 0.3}
	local function step(s, dt, jump, drift, contact, enabled)
		return s:step(dt, input(jump, drift, enabled), contact or ground)
	end
	check("idle has no output", function()
		local r = step(Gesture.new(config), 1, false, false)
		assert(r.mode == "Idle" and r.jumpSpeed == 0 and r.boostSeconds == 0)
	end)
	check("jump tap launches on release once", function()
		local s = Gesture.new(config)
		assert(step(s, 0, true, false).mode == "JumpCharge")
		near(step(s, 0, false, false).jumpSpeed, 10)
		assert(step(s, 1, false, false).jumpSpeed == 0)
	end)
	check("jump reaches maximum and waits for release", function()
		local s = Gesture.new(config)
		near(step(s, 4, true, false).jumpCharge, 1)
		assert(step(s, 4, true, false).jumpSpeed == 0)
		near(step(s, 0, false, false).jumpSpeed, 20)
	end)
	check("drift pressed during charge cannot steal jump", function()
		local s = Gesture.new(config)
		step(s, 0.2, true, false)
		local r = step(s, 0.2, true, true)
		assert(r.mode == "JumpCharge" and not r.drifting)
		near(step(s, 0, false, true).jumpSpeed, 20)
		assert(step(s, 0.5, false, true).mode == "Idle")
	end)
	check("simultaneous press prioritizes jump", function()
		assert(step(Gesture.new(config), 0.1, true, true).mode == "JumpCharge")
	end)
	check("explicit drift hops once and holds through airtime", function()
		local s = Gesture.new(config)
		near(step(s, 0, false, true).jumpSpeed, 10)
		local r = step(s, 1, false, true, air)
		assert(r.mode == "Drift" and not r.diving and r.driftCharge == 0)
		assert(step(s, 0.4, false, true).drifting)
		near(step(s, 0, false, false).boostSeconds, 0.15)
	end)
	check("jump press can leave drift without awarding boost", function()
		local s = Gesture.new(config)
		step(s, 0, false, true); step(s, 1, false, true)
		local r = step(s, 0.1, true, true)
		assert(r.mode == "JumpCharge" and r.boostSeconds == 0)
	end)
	check("airborne drift press cannot dive or launch", function()
		local s = Gesture.new(config)
		assert(step(s, 0.2, false, true, air).mode == "Idle")
		assert(step(s, 0.2, false, true).mode == "Idle")
	end)
	check("drift charge requires support speed and slip", function()
		local s = Gesture.new(config)
		step(s, 0, false, true)
		for _, c in {air, {grounded=true,speed=7,slip=0.3}, {grounded=true,speed=16,slip=0.14}} do
			assert(step(s, 1, false, true, c).driftCharge == 0)
		end
		near(step(s, 0.4, false, true, {grounded=true,speed=8,slip=-0.15}).driftCharge, 0.4/0.9)
	end)
	check("boost tiers cap and emit once", function()
		local s = Gesture.new(config)
		step(s, 0, false, true)
		near(step(s, 3, false, true).driftCharge, 1)
		near(step(s, 0, false, false).boostSeconds, 0.4)
		assert(step(s, 1, false, false).boostSeconds == 0)
	end)
	check("air release can spend earned drift", function()
		local s = Gesture.new(config)
		step(s, 0, false, true); step(s, 0.4, false, true)
		local r = step(s, 0.1, false, false, air)
		near(r.boostSeconds, 0.15); assert(r.jumpSpeed == 0)
	end)
	check("ledge grace freezes charge then launches", function()
		local s = Gesture.new(config)
		step(s, 0.2, true, false)
		near(step(s, 0.05, true, false, air).jumpCharge, 0.5)
		near(step(s, 0, false, false, air).jumpSpeed, 15)
	end)
	check("expired grace cannot launch on landing", function()
		local s = Gesture.new(config)
		step(s, 0.4, true, false); step(s, 0.11, true, false, air)
		assert(step(s, 1, true, false).mode == "Idle")
		assert(step(s, 0, false, false).jumpSpeed == 0)
		assert(step(s, 0.1, true, false).mode == "JumpCharge")
	end)
	check("release after grace expires cannot launch", function()
		local s = Gesture.new(config)
		step(s, 0.4, true, false)
		assert(step(s, 0.11, false, false, air).jumpSpeed == 0)
	end)
	check("charged launch followed by fresh air press dives", function()
		local s = Gesture.new(config)
		step(s, 0.4, true, false); near(step(s, 0, false, false).jumpSpeed, 20)
		assert(not step(s, 0.05, false, false, air).diving)
		assert(step(s, 0.05, true, false, air).diving)
		assert(not step(s, 0.05, false, false, air).diving)
	end)
	check("landing held dive never launches", function()
		local s = Gesture.new(config)
		step(s, 0, true, false, air)
		local r = step(s, 1, true, false)
		assert(not r.diving and r.jumpSpeed == 0 and not r.drifting)
		assert(step(s, 0, false, false).jumpSpeed == 0)
	end)
	check("cancellation requires both actions released before a new press", function()
		for _, drift in {false, true} do
			local s = Gesture.new(config)
			step(s, 0, not drift, drift); step(s, 1, not drift, drift)
			local r = step(s, 0, true, true, ground, false)
			assert(r.mode == "Idle" and r.jumpSpeed == 0 and r.boostSeconds == 0)
			assert(step(s, 1, true, true).mode == "Idle")
			assert(step(s, 1, false, true).mode == "Idle")
			step(s, 0, false, false)
			assert(step(s, 0.1, true, false).mode == "JumpCharge")
		end
	end)
	check("disabled release cancels instead of firing", function()
		for _, drift in {false, true} do
			local s = Gesture.new(config)
			step(s, 0, not drift, drift); step(s, 1, not drift, drift)
			local r = step(s, 0, false, false, ground, false)
			assert(r.jumpSpeed == 0 and r.boostSeconds == 0)
		end
	end)
	check("charge and drift thresholds match at 30 60 120 FPS", function()
		for _, fps in {30,60,120} do
			local s = Gesture.new(config)
			for _=1,fps*0.2 do step(s, 1/fps, true, false) end
			near(step(s, 0, false, false).jumpSpeed, 15)
			s = Gesture.new(config); step(s, 0, false, true)
			for _=1,fps*0.4 do step(s, 1/fps, false, true) end
			near(step(s, 0, false, false).boostSeconds, 0.15)
		end
	end)
	check("queued tap within one tick is preserved", function()
		local s = Gesture.new(config)
		local r = s:stepEvents(1/30, input(false,false), ground, {input(true,false),input(false,false)})
		near(r.jumpSpeed, 10); assert(r.mode == "Idle" and ground.grounded)
	end)
	check("rapid release repress produces one launch and dive", function()
		local s = Gesture.new(config)
		step(s, 0.4, true, false)
		local r = s:stepEvents(1/30,input(true,false),ground,{input(false,false),input(true,false)})
		near(r.jumpSpeed,20); assert(r.diving)
	end)
	check("repeated edges cannot stack launches", function()
		local s = Gesture.new(config)
		local edges = {}
		for _=1,4 do table.insert(edges,input(true,false));table.insert(edges,input(false,false)) end
		near(s:stepEvents(0.2,input(false,false),ground,edges).jumpSpeed,10)
	end)
	check("queued drift release and repress preserve boost and hop", function()
		local s = Gesture.new(config)
		step(s,0,false,true);step(s,0.4,false,true)
		local r = s:stepEvents(0.1,input(false,true),ground,{input(false,false),input(false,true)})
		near(r.boostSeconds,0.15);near(r.jumpSpeed,10)
	end)
	check("disabled frame discards queued charge", function()
		local s = Gesture.new(config)
		step(s,0.4,true,false)
		local r = s:stepEvents(0.1,input(false,false,false),ground,{input(false,false),input(false,true)})
		assert(r.mode == "Idle" and r.jumpSpeed == 0 and r.boostSeconds == 0)
	end)
	check("edge overflow cancels and requires release", function()
		local s = Gesture.new(config)
		local r = s:stepEvents(0.1,input(true,false),ground,table.create(9,input(true,false)))
		assert(r.mode == "Idle" and r.jumpSpeed == 0)
		assert(step(s,1,true,false).mode == "Idle")
		step(s,0,false,false);assert(step(s,0.1,true,false).mode == "JumpCharge")
	end)
	return {passed=passed}
end
